// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using amorphie.contract.data.Contexts;

#nullable disable

namespace amorphie.contract.data.Migrations.Pg
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20230518075824_MyMigration6")]
    partial class MyMigration6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentDefinitionDocumentGroup", b =>
                {
                    b.Property<Guid>("DocumentDefinitionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentGroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentDefinitionsId", "DocumentGroupsId");

                    b.HasIndex("DocumentGroupsId");

                    b.ToTable("DocumentDefinitionDocumentGroup", "Definition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Language", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentContentId");

                    b.HasIndex("DocumentDefinitionId");

                    b.ToTable("Document", "Definition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentVersionsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionsId");

                    b.ToTable("DocumentContent", "Definition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("LanguageId");

                    b.ToTable("DocumentDefinition", "Definition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("DocumentGroupId");

                    b.HasIndex("LanguageId");

                    b.ToTable("DocumentGroup", "Definition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentGroupDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDefinitionId");

                    b.HasIndex("DocumentGroupId");

                    b.ToTable("DocumentGroupDetail", "Definition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDefinitionId");

                    b.ToTable("DocumentTemplate", "Definition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDefinitionId");

                    b.ToTable("DocumentType", "Definition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentVersions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDefinitionId");

                    b.ToTable("DocumentVersions", "Definition");
                });

            modelBuilder.Entity("DocumentDefinitionDocumentGroup", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentDefinition", null)
                        .WithMany()
                        .HasForeignKey("DocumentDefinitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentGroup", null)
                        .WithMany()
                        .HasForeignKey("DocumentGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.Document", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentContent", "DocumentContent")
                        .WithMany()
                        .HasForeignKey("DocumentContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentDefinition", "DocumentDefinition")
                        .WithMany()
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentContent");

                    b.Navigation("DocumentDefinition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentContent", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentVersions", "DocumentVersions")
                        .WithMany()
                        .HasForeignKey("DocumentVersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentVersions");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentDefinition", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentGroup", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentGroup", null)
                        .WithMany("DocumentGroups")
                        .HasForeignKey("DocumentGroupId");

                    b.HasOne("amorphie.contract.core.Entity.Common.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentGroupDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentDefinition", "DocumentDefinition")
                        .WithMany("DocumentGroupDetails")
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentGroup", "DocumentGroup")
                        .WithMany()
                        .HasForeignKey("DocumentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentDefinition");

                    b.Navigation("DocumentGroup");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentTemplate", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentDefinition", null)
                        .WithMany("DocumentTemplates")
                        .HasForeignKey("DocumentDefinitionId");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentType", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentDefinition", null)
                        .WithMany("DocumentTypes")
                        .HasForeignKey("DocumentDefinitionId");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentVersions", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Definition.DocumentDefinition", "DocumentDefinition")
                        .WithMany()
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentDefinition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentDefinition", b =>
                {
                    b.Navigation("DocumentGroupDetails");

                    b.Navigation("DocumentTemplates");

                    b.Navigation("DocumentTypes");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Definition.DocumentGroup", b =>
                {
                    b.Navigation("DocumentGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
