// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using amorphie.contract.data.Contexts;

#nullable disable

namespace amorphie.contract.data.Migrations.Pg
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20231005140644_ContractMigrations")]
    partial class ContractMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.LanguageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LanguageType", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.MultiLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("LanguageTypeId");

                    b.ToTable("MultiLanguage", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Status", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tag", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.Validation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ValidationDecisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ValidationDecisionId");

                    b.ToTable("Validation", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.ValidationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ValidationDecisionTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ValidationDecisionTypeId");

                    b.ToTable("ValidationDecision", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.ValidationDecisionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ValidationDecisionType", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.Versions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Versions", "Common");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("ContractDefinition", "Cont");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractDocumentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<int>("UseExisting")
                        .HasColumnType("integer");

                    b.Property<Guid>("VersionsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractDefinitionId");

                    b.HasIndex("DocumentDefinitionId");

                    b.HasIndex("VersionsId");

                    b.ToTable("ContractDocumentDetail", "Cont");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractDocumentGroupDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AtLeastRequiredDocument")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ContractDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ContractDefinitionId");

                    b.HasIndex("DocumentGroupId");

                    b.ToTable("ContractDocumentGroupDetail", "Cont");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractEntityProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityPropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractDefinitionId");

                    b.HasIndex("EntityPropertyId");

                    b.ToTable("ContractEntityProperty", "Cont");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractDefinitionId");

                    b.HasIndex("TagId");

                    b.ToTable("ContractTag", "Cont");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ValidationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractDefinitionId");

                    b.HasIndex("ValidationId");

                    b.ToTable("ContractValidation", "Cont");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentContentId");

                    b.HasIndex("DocumentDefinitionId");

                    b.ToTable("Document", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentAllowedClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DocumentAllowedClient", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentAllowedClientDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentAllowedClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentOnlineSingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentRenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentUploadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentAllowedClientId");

                    b.HasIndex("DocumentOnlineSingId");

                    b.HasIndex("DocumentRenderId");

                    b.HasIndex("DocumentUploadId");

                    b.ToTable("DocumentAllowedClientDetail", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("KiloBytesSize")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId");

                    b.ToTable("DocumentContent", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentOnlineSingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentOperationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentOperationsId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentOptimizeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentOptimizeId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentRenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentUploadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseStatusId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DocumentOnlineSingId");

                    b.HasIndex("DocumentOperationsId1");

                    b.HasIndex("DocumentOptimizeId1");

                    b.HasIndex("DocumentRenderId");

                    b.HasIndex("DocumentUploadId");

                    b.HasIndex("StatusId");

                    b.ToTable("DocumentDefinition", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentDefinitionLanguageDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MultiLanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDefinitionId");

                    b.HasIndex("MultiLanguageId");

                    b.ToTable("DocumentDefinitionLanguageDetail", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentEntityProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityPropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDefinitionId");

                    b.HasIndex("EntityPropertyId");

                    b.ToTable("DocumentEntityProperty", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormIO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LanguageTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LanguageTypeId");

                    b.ToTable("DocumentFormIO", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormIODetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentFormIOId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentRenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentFormIOId");

                    b.HasIndex("DocumentRenderId");

                    b.ToTable("DocumentFormIODetail", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentFormatTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentSizeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentFormatTypeId");

                    b.HasIndex("DocumentSizeId");

                    b.ToTable("DocumentFormat", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormatDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentFormatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentUploadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentFormatId");

                    b.HasIndex("DocumentUploadId");

                    b.ToTable("DocumentFormatDetail", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormatType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DocumentFormatType", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("DocumentGroup", "DocGroup");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroupDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentGroupID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDefinitionId");

                    b.HasIndex("DocumentGroupID");

                    b.ToTable("DocumentGroupDetail", "DocGroup");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroupLanguageDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MultiLanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentGroupId");

                    b.HasIndex("MultiLanguageId");

                    b.ToTable("DocumentGroupLanguageDetail", "DocGroup");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentOperations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DocumentManuelControl")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentOperations", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentOptimize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentOptimizeTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<bool>("Size")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DocumentOptimizeTypeId");

                    b.ToTable("DocumentOptimize", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentOptimizeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DocumentOptimizeType", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<decimal>("KiloBytes")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DocumentSize", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTagsDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDefinitionId");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentTag", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LanguageTypeId");

                    b.ToTable("DocumentTemplate", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTemplateDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentOnlineSingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentRenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentOnlineSingId");

                    b.HasIndex("DocumentRenderId");

                    b.HasIndex("DocumentTemplateId");

                    b.ToTable("DocumentTemplateDetail", "Doc");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentOnlineSing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<Guid>("VersionsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId");

                    b.ToTable("DocumentOnlineSing", "DocTp");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentRender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionsId");

                    b.ToTable("DocumentRender", "DocTp");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DocumentUpload", "DocTp");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.EAV.EntityProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityPropertyTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityPropertyValueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EntityPropertyTypeId");

                    b.HasIndex("EntityPropertyValueId");

                    b.ToTable("EntityProperty", "EAV");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.EAV.EntityPropertyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EntityPropertyType", "EAV");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.EAV.EntityPropertyValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBehalfOf")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedByBehalfOf")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EntityPropertyValue", "EAV");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.MultiLanguage", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.LanguageType", "LanguageType")
                        .WithMany()
                        .HasForeignKey("LanguageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageType");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.Validation", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.ValidationDecision", "ValidationDecision")
                        .WithMany()
                        .HasForeignKey("ValidationDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValidationDecision");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Common.ValidationDecision", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.ValidationDecisionType", "ValidationDecisionTypes")
                        .WithMany()
                        .HasForeignKey("ValidationDecisionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValidationDecisionTypes");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractDefinition", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractDocumentDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Contract.ContractDefinition", null)
                        .WithMany("ContractDocumentDetails")
                        .HasForeignKey("ContractDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentDefinition", "DocumentDefinition")
                        .WithMany()
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Common.Versions", "Versions")
                        .WithMany()
                        .HasForeignKey("VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentDefinition");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractDocumentGroupDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Contract.ContractDefinition", null)
                        .WithMany("ContractDocumentGroupDetails")
                        .HasForeignKey("ContractDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroup", "DocumentGroup")
                        .WithMany()
                        .HasForeignKey("DocumentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentGroup");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractEntityProperty", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Contract.ContractDefinition", null)
                        .WithMany("ContractEntityProperty")
                        .HasForeignKey("ContractDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.EAV.EntityProperty", "EntityProperty")
                        .WithMany()
                        .HasForeignKey("EntityPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityProperty");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractTag", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Contract.ContractDefinition", null)
                        .WithMany("ContractTags")
                        .HasForeignKey("ContractDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Common.Tag", "Tags")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractValidation", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Contract.ContractDefinition", null)
                        .WithMany("ContractValidations")
                        .HasForeignKey("ContractDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Common.Validation", "Validations")
                        .WithMany()
                        .HasForeignKey("ValidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Validations");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.Document", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentContent", "DocumentContent")
                        .WithMany()
                        .HasForeignKey("DocumentContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentDefinition", "DocumentDefinition")
                        .WithMany()
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentContent");

                    b.Navigation("DocumentDefinition");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentAllowedClientDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentFormat", "DocumentAllowedClient")
                        .WithMany()
                        .HasForeignKey("DocumentAllowedClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentOnlineSing", null)
                        .WithMany("DocumentAllowedClientDetails")
                        .HasForeignKey("DocumentOnlineSingId");

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentRender", null)
                        .WithMany("DocumentAllowedClientDetails")
                        .HasForeignKey("DocumentRenderId");

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentUpload", null)
                        .WithMany("DocumentAllowedClientDetails")
                        .HasForeignKey("DocumentUploadId");

                    b.Navigation("DocumentAllowedClient");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentContent", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.Versions", "Versions")
                        .WithMany()
                        .HasForeignKey("VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentDefinition", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.Status", "BaseStatus")
                        .WithMany()
                        .HasForeignKey("BaseStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentOnlineSing", "DocumentOnlineSing")
                        .WithMany()
                        .HasForeignKey("DocumentOnlineSingId");

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentOperations", "DocumentOperations")
                        .WithMany()
                        .HasForeignKey("DocumentOperationsId1");

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentOptimize", "DocumentOptimize")
                        .WithMany()
                        .HasForeignKey("DocumentOptimizeId1");

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentRender", "DocumentRender")
                        .WithMany()
                        .HasForeignKey("DocumentRenderId");

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentUpload", "DocumentUpload")
                        .WithMany()
                        .HasForeignKey("DocumentUploadId");

                    b.HasOne("amorphie.contract.core.Entity.Common.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseStatus");

                    b.Navigation("DocumentOnlineSing");

                    b.Navigation("DocumentOperations");

                    b.Navigation("DocumentOptimize");

                    b.Navigation("DocumentRender");

                    b.Navigation("DocumentUpload");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentDefinitionLanguageDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentDefinition", null)
                        .WithMany("DocumentDefinitionLanguageDetails")
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Common.MultiLanguage", "MultiLanguage")
                        .WithMany()
                        .HasForeignKey("MultiLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultiLanguage");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentEntityProperty", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentDefinition", null)
                        .WithMany("DocumentEntityPropertys")
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.EAV.EntityProperty", "EntityProperty")
                        .WithMany()
                        .HasForeignKey("EntityPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityProperty");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormIO", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.LanguageType", "LanguageType")
                        .WithMany()
                        .HasForeignKey("LanguageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageType");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormIODetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentFormIO", "DocumentFormIO")
                        .WithMany()
                        .HasForeignKey("DocumentFormIOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentRender", null)
                        .WithMany("DocumentFormIODetail")
                        .HasForeignKey("DocumentRenderId");

                    b.Navigation("DocumentFormIO");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormat", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentFormatType", "DocumentFormatType")
                        .WithMany()
                        .HasForeignKey("DocumentFormatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentSize", "DocumentSize")
                        .WithMany()
                        .HasForeignKey("DocumentSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentFormatType");

                    b.Navigation("DocumentSize");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentFormatDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentFormat", "DocumentFormat")
                        .WithMany()
                        .HasForeignKey("DocumentFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentUpload", null)
                        .WithMany("DocumentFormatDetails")
                        .HasForeignKey("DocumentUploadId");

                    b.Navigation("DocumentFormat");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroup", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroupDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentDefinition", "DocumentDefinition")
                        .WithMany()
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroup", "DocumentGroup")
                        .WithMany("DocumentGroupDetails")
                        .HasForeignKey("DocumentGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentDefinition");

                    b.Navigation("DocumentGroup");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroupLanguageDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroup", "DocumentGroup")
                        .WithMany("DocumentGroupLanguageDetail")
                        .HasForeignKey("DocumentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Common.MultiLanguage", "MultiLanguage")
                        .WithMany()
                        .HasForeignKey("MultiLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentGroup");

                    b.Navigation("MultiLanguage");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentOperations", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.Tag", "Tags")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentOptimize", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentOptimizeType", "DocumentOptimizeType")
                        .WithMany()
                        .HasForeignKey("DocumentOptimizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentOptimizeType");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTagsDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentDefinition", null)
                        .WithMany("DocumentTagsDetails")
                        .HasForeignKey("DocumentDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.Common.Tag", "Tags")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTemplate", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.LanguageType", "LanguageType")
                        .WithMany()
                        .HasForeignKey("LanguageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageType");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTemplateDetail", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentOnlineSing", null)
                        .WithMany("DocumentTemplateDetails")
                        .HasForeignKey("DocumentOnlineSingId");

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentRender", null)
                        .WithMany("DocumentTemplateDetails")
                        .HasForeignKey("DocumentRenderId");

                    b.HasOne("amorphie.contract.core.Entity.Document.DocumentTemplate", "DocumentTemplate")
                        .WithMany()
                        .HasForeignKey("DocumentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentTemplate");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentOnlineSing", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.Versions", "Versions")
                        .WithMany()
                        .HasForeignKey("VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentRender", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.Common.Versions", "Versions")
                        .WithMany()
                        .HasForeignKey("VersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.EAV.EntityProperty", b =>
                {
                    b.HasOne("amorphie.contract.core.Entity.EAV.EntityPropertyType", "EntityPropertyType")
                        .WithMany()
                        .HasForeignKey("EntityPropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amorphie.contract.core.Entity.EAV.EntityPropertyValue", "EntityPropertyValue")
                        .WithMany()
                        .HasForeignKey("EntityPropertyValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityPropertyType");

                    b.Navigation("EntityPropertyValue");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Contract.ContractDefinition", b =>
                {
                    b.Navigation("ContractDocumentDetails");

                    b.Navigation("ContractDocumentGroupDetails");

                    b.Navigation("ContractEntityProperty");

                    b.Navigation("ContractTags");

                    b.Navigation("ContractValidations");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentDefinition", b =>
                {
                    b.Navigation("DocumentDefinitionLanguageDetails");

                    b.Navigation("DocumentEntityPropertys");

                    b.Navigation("DocumentTagsDetails");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentGroups.DocumentGroup", b =>
                {
                    b.Navigation("DocumentGroupDetails");

                    b.Navigation("DocumentGroupLanguageDetail");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentOnlineSing", b =>
                {
                    b.Navigation("DocumentAllowedClientDetails");

                    b.Navigation("DocumentTemplateDetails");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentRender", b =>
                {
                    b.Navigation("DocumentAllowedClientDetails");

                    b.Navigation("DocumentFormIODetail");

                    b.Navigation("DocumentTemplateDetails");
                });

            modelBuilder.Entity("amorphie.contract.core.Entity.Document.DocumentTypes.DocumentUpload", b =>
                {
                    b.Navigation("DocumentAllowedClientDetails");

                    b.Navigation("DocumentFormatDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
