version: '3.9'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-contractminio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-contract123456}
    command: server /data --console-address ":9001"
    networks:
      - contract-local
      #OIDC lazım..

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-contractdb}
      POSTGRES_USER: ${POSTGRES_USER:-contractpostgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    networks:
      - contract-local

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-contract@amorphie.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres
    networks:
      - contract-local

  zookeeper1:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - contract-local
  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    depends_on:
      - zookeeper1
    ports:
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,PLAINTEXT1://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= PLAINTEXT:PLAINTEXT, PLAINTEXT1:PLAINTEXT
    networks:
      - contract-local
  kafka-ui1:
    container_name: kafka-ui1
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka1
    environment:
      - KAFKA_CLUSTERS_0_NAME= local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS= kafka1:9092
      - DYNAMIC_CONFIG_ENABLED= 'true'
    networks:
      - contract-local

networks:
  contract-local:
    driver: bridge

volumes:
  minio:
  postgres:
  pgadmin:
