apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: contract-pubsub-kafka
spec:
  type: pubsub.kafka
  metadata:
      # Kafka broker connection setting
    - name: brokers
      # Comma separated list of kafka brokers
      value: "localhost:29092"
      # Enable auth. Default is "false"
    - name: authType
      value: "none"

